### ISSUE TITLE
Build failing with stmts.entries is not a function

### ISSUE THREAD

**Issue by Kif11** [supermedium/aframe-super-hot-loader#2]
I get this error on `yarn build` for the example project. Did you experience something like this?

```
ERROR in unknown: stmts.entries is not a function
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
$: grep -r stmts.entries .
./node_modules/babel-helper-evaluate-path/lib/index.js:    for (var _iterator = stmts.entries()[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
```

**Comment by uhunkler** [comment]
I have the same issue using npm and the build script.

**Comment by uhunkler** [comment]
I got the build process working after I changed »webpack.config.js« on line 12 to exclude the minify plugin.

original:
if (process.env.NODE_ENV === 'production') {
changed to:
if (process.env.NODE_ENV === '_production') {

**Comment by Kif11** [comment]
@uhunkler What is "_production"? (with underscore)

**Comment by uhunkler** [comment]
It is a hack - I used »_production« to make sure that the minify plugin is not started. You may also write something like 'dontminify' or anything.

**Comment by ngokevin** [comment]
Fixed yesterday, thanks! https://github.com/supermedium/aframe-super-hot-loader/commit/2d7ce00e7a4ebeed4e6cd9e649beaf65ca289efe
